version: 2.1 # Use v2.1 to enable orb usage.

# The Windows orb gives you everything you
# need to start using the Windows executor.
orbs:
  win: circleci/windows@2.2.0
  azure-cli: circleci/azure-cli@1.1.0

jobs:
  test_azure:
    description: Test interaction with Azure CLI
    executor: azure-cli/azure-docker
    steps:
      # - azure-cli/login-with-service-principal
      # - run:
      #     name: az login
      #     command: az login -u $AZURE_CLIENT_URL -p $AZURE_CLIENT_SECRET -t $AZURE_TENANT_ID
      # Needs AZURE_SP_TENANT, AZURE_SP (url) and AZURE_SP_PASSWORD env vars
      - azure-cli/login-with-service-principal
      - checkout:
          path: C:\Users\circleci\project
      - run:
          name: List Azure Resources
          command: sh scripts/azList.sh

  test_env_vars:
    description: Testing environment variables
    executor: win/default

    steps:
      - checkout:
          path: C:\Users\circleci\project
      - run:
          name: Run a script
          command: pwsh ./scripts/sayHello.ps1
      - run: Write-Host "Deploy App"
      - run: Write-Host $Env:TEST_VALUE_BOOLEAN
      - run: Write-Host $Env:TEST_VALUE_NUM
      

  build_and_test: # name of your job
    description: Build & Test
    executor: win/default # executor type

    steps:
      # Commands are run in a Windows
      # virtual machine environment
      - checkout:
          path: C:\Users\circleci\project
      - run:
          name: Nuget Restore
          command: nuget restore HelloApi\HelloApi.sln
      - run:
          name: Build Debug
          command: |
            msbuild HelloApi\HelloApi.sln /p:Configuration=Debug
      - run:
          name: Run Tests
          command: |
            cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\common7\ide\extensions\TestPlatform"
            .\vstest.console.exe "C:\Users\circleci\project\HelloApi\HelloApi.Tests\bin\debug\HelloApi.Tests.dll"
  build_release: # name of your job  
    description: Build Release
    executor: win/default # executor type

    steps:
      # Commands are run in a Windows
      # virtual machine environment
      - checkout:
          path: C:\Users\circleci\project
      - run:
          name: Nuget Restore
          command: nuget restore HelloApi\HelloApi.sln
      - run:
          name: Build Release
          command: |
            msbuild HelloApi\HelloApi.sln /p:Configuration=Release
  deploy:
    description: Deploy Application
    executor: win/default

    steps:
      - checkout:
          path: C:\Users\circleci\project

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test_azure
      # - test_env_vars
      # - build_and_test
      # - build_release:
      #     requires:
      #       - build_and_test
      # - deploy:
      #     requires:
      #       - build_release
      #     filters:
      #       branches:
      #         only: master