version: 2.1 # Use v2.1 to enable orb usage.

# The Windows orb gives you everything you
# need to start using the Windows executor.
orbs:
  win: circleci/windows@2.2.0

jobs:
  build: # name of your job
    executor: win/default # executor type

    steps:
      # Commands are run in a Windows
      # virtual machine environment
      - checkout:
          path: C:\Users\circleci\project
      - run: msbuild -t:restore;build HelloApi\HelloApi.sln /p:Configuration=Debug
      - run:
          name: Look at files
          command: |
            dir
            cd "HelloApi"
            dir
            cd "HelloApi.Tests"
            dir
            cd "bin"
            dir
            cd "Debug"
            dir
      - run:
          name: Run Tests
          command: |
            cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\common7\ide\extensions\TestPlatform"
            .\vstest.console.exe "C:\Users\circleci\project\HelloApi\HelloApi.Tests\bin\debug\HelloApi.Tests.dll"