version: 2.1 # Use v2.1 to enable orb usage.

# The Windows orb gives you everything you
# need to start using the Windows executor.
orbs:
  win: circleci/windows@2.2.0

jobs:
  build_and_test: # name of your job
    description: Build & Test
    executor: win/default # executor type

    steps:
      # Commands are run in a Windows
      # virtual machine environment
      - checkout:
          path: C:\Users\circleci\project
      - run:
          name: Nuget Restore
          command: nuget restore HelloApi\HelloApi.sln
      - run:
          name: Build Debug
          command: |
            msbuild HelloApi\HelloApi.sln /p:Configuration=Debug
      - run:
          name: Run Tests
          command: |
            cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\common7\ide\extensions\TestPlatform"
            .\vstest.console.exe "C:\Users\circleci\project\HelloApi\HelloApi.Tests\bin\debug\HelloApi.Tests.dll"
      - run:
          name: Build Release
          command: |
            msbuild HelloApi\HelloApi.sln /p:Configuration=Release
  build_release: # name of your job  
    description: Build Release
    executor: win/default # executor type

    steps:
      # Commands are run in a Windows
      # virtual machine environment
      - checkout:
          path: C:\Users\circleci\project
      - run:
          name: Build Release
          command: |
            msbuild HelloApi\HelloApi.sln /p:Configuration=Release
  deploy:
    description: Deploy Application
    executor: win/default

    steps:
      - checkout:
          path: C:\Users\circleci\project
      - run: Write-Host "Deploy App"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_test
      - build_release:
          requires:
            - build_and_test
      - deploy:
          requires:
            - build_release
          filters:
            branches:
              only: master